server:
  port: 8088
web:
  domain: http://localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/doubao?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource

#rabbitmq配置相关链接信息
  application:
    name: mq-springboot
  rabbitmq:
    host: 192.168.126.130
    port: 5672
    username: root
    password: root
    virtual-host: myhost
# RabbitMQ消息确认机制
# 消息发送到交换器确认
spring.rabbitmq.publisher-confirm-type: correlated
# 消息发送到队列确认
spring.rabbitmq.publisher-returns: true
# 消费者消息确认--手动 ACK
spring.rabbitmq.listener.direct.acknowledge-mode: manual
spring.rabbitmq.listener.simple.acknowledge-mode: manual

#打印sql日志信息
logging:
  level:
    root: info
    com.douyuehan.doubao: debug

#redis配置
#sudo systemctl stop firewalld.service #停止firewall
#sudo systemctl disable firewalld.service #禁止firewall开机启动
spring.redis.host: 192.168.126.130
spring.redis.port: 6379
spring.redis.password: 123456
spring.redis.database: 0
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.jedis.pool.max-active: 100
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.jedis.pool.max-wait: 5000
# 连接池中的最大空闲连接
spring.redis.jedis.pool.max-idle: 10
# 连接池中的最小空闲连接
spring.redis.jedis.pool.min-idle: 0
# 连接超时时间（毫秒）
spring.redis.timeout: 5000



